/* NOTE -- generated by scripts/ab_gen_iddefines.pl -- DO NOT EDIT */
/* ab_gen_iddefines.pl 2016-01-29 */

#ifndef __IDS_part1__
#define __IDS_part1__

#define CFG_PART_NAME	part1
#define CFG_PART_NAME_STR	"part1"
#define CFG_PART_ID	0
#define CFG_MAX_PRIO	200
#define CFG_PART_CPU	0
#define CFG_PART_TIMEPART	0
/* CFG_NUM_ERROR_RECORDS not defined */

#define CFG_TASK_main	0
#define CFG_TASK_main_PRIO	102
#define CFG_TASK_SteeringTask	1
#define CFG_TASK_SteeringTask_PRIO	104
#define CFG_TASK_PWRTrainTask	2
#define CFG_TASK_PWRTrainTask_PRIO	103
#define CFG_NUM_TASKS	3

#define CFG_ISR_VR_IRQ	3
#define CFG_ISR_VR_IRQ_PRIO	109
#define CFG_ISR_VL_IRQ	4
#define CFG_ISR_VL_IRQ_PRIO	107
#define CFG_ISR_HR_IRQ	5
#define CFG_ISR_HR_IRQ_PRIO	110
#define CFG_ISR_HL_IRQ	6
#define CFG_ISR_HL_IRQ_PRIO	108
#define CFG_ISR_PWR_IRQ	7
#define CFG_ISR_PWR_IRQ_PRIO	112
#define CFG_ISR_STR_IRQ	8
#define CFG_ISR_STR_IRQ_PRIO	113
#define CFG_ISR_DIS_IRQ	9
#define CFG_ISR_DIS_IRQ_PRIO	120
#define CFG_ISR_ULTR_IRQ	10
#define CFG_ISR_ULTR_IRQ_PRIO	111
#define CFG_NUM_ISRS	8

#define CFG_HOOK__start	11
#define CFG_HOOK__start_PRIO	102
#define CFG_NUM_HOOKS	1

#define CFG_INIT_HOOK_ID	11
/* CFG_ERROR_HOOK_ID not defined */
/* CFG_EXCEPTION_HOOK_ID not defined */

#define CFG_NUM_INVOKABLES	0

#define CFG_NUM_RPCS	0

#define CFG_NUM_SHMS	0

#define CFG_KLDD_gpio_wr	0
#define CFG_KLDD_gpio_re	1
#define CFG_KLDD_gpio_toggle	2
#define CFG_KLDD_gpio_s	3
#define CFG_KLDD_gpio_res	4
#define CFG_NUM_KLDDS	5

#define CFG_NUM_IPEVS	0

#define CFG_NUM_COUNTERS	0

#define CFG_NUM_ALARMS	0

#define CFG_SCHEDTAB_car	0
#define CFG_SCHEDTAB_car_DURATION	6
#define CFG_NUM_SCHEDTABS	1

#define CFG_NUM_WQS	0


#endif
