/* NOTE -- generated by scripts/ab_gen_lddefines.pl -- DO NOT EDIT */
/* ab_gen_lddefines.pl 2016-01-29 */
/* NOTE: this file contains the final relocation information */

#ifndef __LDS_part1__
#define __LDS_part1__

#define SECTION_START_text	0x08014000
#define SECTION_SIZE_text	0x00004000
#define SECTION_START_data	0x20004000
#define SECTION_SIZE_data	0x00004000

#endif
