/*
 * blackboard.c
 *
 * ARINC blackboards.
 *
 * azuepke, 2014-09-04: initial
 */

#include "apex.h"

void CREATE_BLACKBOARD (
/*in */ BLACKBOARD_NAME_TYPE BLACKBOARD_NAME,
/*in */ MESSAGE_SIZE_TYPE MAX_MESSAGE_SIZE,
/*out*/ BLACKBOARD_ID_TYPE *BLACKBOARD_ID,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE )
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)BLACKBOARD_NAME;
	(void)MAX_MESSAGE_SIZE;
	(void)BLACKBOARD_ID;
	*RETURN_CODE = 42;
}

void DISPLAY_BLACKBOARD (
/*in */ BLACKBOARD_ID_TYPE BLACKBOARD_ID,
/*in */ MESSAGE_ADDR_TYPE MESSAGE_ADDR, /* by reference */
/*in */ MESSAGE_SIZE_TYPE LENGTH,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE )
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)BLACKBOARD_ID;
	(void)MESSAGE_ADDR;
	(void)LENGTH;
	*RETURN_CODE = 42;
}

void READ_BLACKBOARD (
/*in */ BLACKBOARD_ID_TYPE BLACKBOARD_ID,
/*in */ SYSTEM_TIME_TYPE TIME_OUT,
/*out*/ MESSAGE_ADDR_TYPE MESSAGE_ADDR,
/*out*/ MESSAGE_SIZE_TYPE *LENGTH,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE )
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)BLACKBOARD_ID;
	(void)TIME_OUT;
	(void)MESSAGE_ADDR;
	(void)LENGTH;
	*RETURN_CODE = 42;
}

void CLEAR_BLACKBOARD (
/*in */ BLACKBOARD_ID_TYPE BLACKBOARD_ID,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE )
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)BLACKBOARD_ID;
	*RETURN_CODE = 42;
}

void GET_BLACKBOARD_ID (
/*in */ BLACKBOARD_NAME_TYPE BLACKBOARD_NAME,
/*out*/ BLACKBOARD_ID_TYPE *BLACKBOARD_ID,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE )
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)BLACKBOARD_NAME;
	(void)BLACKBOARD_ID;
	*RETURN_CODE = 42;
}

void GET_BLACKBOARD_STATUS (
/*in */ BLACKBOARD_ID_TYPE BLACKBOARD_ID,
/*out*/ BLACKBOARD_STATUS_TYPE *BLACKBOARD_STATUS,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE )
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)BLACKBOARD_ID;
	(void)BLACKBOARD_STATUS;
	*RETURN_CODE = 42;
}
