/*
 * qport.c
 *
 * ARINC queuing ports.
 *
 * azuepke, 2014-09-08: initial
 */

#include "apex.h"

void CREATE_QUEUING_PORT (
/*in */ QUEUING_PORT_NAME_TYPE QUEUING_PORT_NAME,
/*in */ MESSAGE_SIZE_TYPE MAX_MESSAGE_SIZE,
/*in */ MESSAGE_RANGE_TYPE MAX_NB_MESSAGE,
/*in */ PORT_DIRECTION_TYPE PORT_DIRECTION,
/*in */ QUEUING_DISCIPLINE_TYPE QUEUING_DISCIPLINE,
/*out*/ QUEUING_PORT_ID_TYPE *QUEUING_PORT_ID,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE )
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)QUEUING_PORT_NAME;
	(void)MAX_MESSAGE_SIZE;
	(void)MAX_NB_MESSAGE;
	(void)PORT_DIRECTION;
	(void)QUEUING_DISCIPLINE;
	(void)QUEUING_PORT_ID;
	*RETURN_CODE = 42;
}

void SEND_QUEUING_MESSAGE (
/*in */ QUEUING_PORT_ID_TYPE QUEUING_PORT_ID,
/*in */ MESSAGE_ADDR_TYPE MESSAGE_ADDR, /* by reference */
/*in */ MESSAGE_SIZE_TYPE LENGTH,
/*in */ SYSTEM_TIME_TYPE TIME_OUT,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE)
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)QUEUING_PORT_ID;
	(void)MESSAGE_ADDR;
	(void)LENGTH;
	(void)TIME_OUT;
	*RETURN_CODE = 42;
}

void RECEIVE_QUEUING_MESSAGE (
/*in */ QUEUING_PORT_ID_TYPE QUEUING_PORT_ID,
/*in */ SYSTEM_TIME_TYPE TIME_OUT,
/*out*/ MESSAGE_ADDR_TYPE MESSAGE_ADDR,
/*out*/ MESSAGE_SIZE_TYPE *LENGTH,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE )
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)QUEUING_PORT_ID;
	(void)TIME_OUT;
	(void)MESSAGE_ADDR;
	(void)LENGTH;
	*RETURN_CODE = 42;
}

void GET_QUEUING_PORT_ID (
/*in */ QUEUING_PORT_NAME_TYPE QUEUING_PORT_NAME,
/*out*/ QUEUING_PORT_ID_TYPE *QUEUING_PORT_ID,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE )
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)QUEUING_PORT_NAME;
	(void)QUEUING_PORT_ID;
	*RETURN_CODE = 42;
}

void GET_QUEUING_PORT_STATUS (
/*in */ QUEUING_PORT_ID_TYPE QUEUING_PORT_ID,
/*out*/ QUEUING_PORT_STATUS_TYPE *QUEUING_PORT_STATUS,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE )
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)QUEUING_PORT_ID;
	(void)QUEUING_PORT_STATUS;
	*RETURN_CODE = 42;
}

void CLEAR_QUEUING_PORT (
/*in */ QUEUING_PORT_ID_TYPE QUEUING_PORT_ID,
/*out*/ RETURN_CODE_TYPE *RETURN_CODE )
{
	// FIXME: IMPLEMENTME
	assert(0);
	(void)QUEUING_PORT_ID;
	*RETURN_CODE = 42;
}
