#!/bin/bash
#
# Script to generate syscall header
#
# NOTE: Run this script to generate the syscall header.
#
# azuepke, 2013-05-07: initial

if [ ! -f "$1" ]; then
	echo "usage: $0 <file_with_list_of_syscalls>"
	echo "  creates syscalls.h with increasing syscall IDs"
	exit
fi

set -u -e

FILE=syscalls.h

cat <<- EOF > $FILE
	/* $FILE -- syscall IDs */
	/* GENERATED BY scripts/generate_syscall_header.sh -- DO NOT EDIT */

EOF

ID=0
while read FUNC NAME ARGS32 ARGS64 ALIASES; do
	if [ ! -z "$FUNC" -a "$FUNC" != "#" ]; then
		cat <<- EOF >> $FILE
			#define $NAME	$ID
		EOF
		ID=$(($ID + 1))
	fi
done < $1

cat <<- EOF >> $FILE

	#define NUM_SYSCALLS $ID
EOF
