/*
 * pinmux.c
 *
 * TMS570 pin multiplexing
 *
 * azuepke, 2014-04-24: initial (imported from HalCoGen generated code)
 */

#include <board_stuff.h>
#include <stdint.h>
#include <assert.h>
#include <pinmux.h>

/*LDRA_INSPECTWINDOW 50 */
/*SAFETYMCUSW 125 S MR: 19.13 REVIEWED " Needs usage of ## in the macro " */
/*SAFETYMCUSW 76 S MR: 19.12 REVIEWED " Needs usage of multiple ## in the macro " */
/*SAFETYMCUSW 78 S MR: 19.10 REVIEWED " Macro parameter used for concatenation " */
/*SAFETYMCUSW 78 S MR: 19.10 REVIEWED " Macro parameter used for concatenation " */
/*SAFETYMCUSW 78 S MR: 19.10 REVIEWED " Macro parameter used for concatenation " */
/*SAFETYMCUSW 78 S MR: 19.10 REVIEWED " Macro parameter used for concatenation " */
/*SAFETYMCUSW 78 S MR: 19.10 REVIEWED " Macro parameter used for concatenation " */
/*SAFETYMCUSW 76 S MR: 19.12 REVIEWED " Needs usage of multiple ## in the macro " */
/*SAFETYMCUSW 76 S MR: 19.12 REVIEWED " Needs usage of multiple ## in the macro " */
/*SAFETYMCUSW 76 S MR: 19.12 REVIEWED " Needs usage of multiple ## in the macro " */
/*SAFETYMCUSW 76 S MR: 19.12 REVIEWED " Needs usage of multiple ## in the macro " */
/*SAFETYMCUSW 76 S MR: 19.12 REVIEWED " Needs usage of multiple ## in the macro " */
/*SAFETYMCUSW 76 S MR: 19.12 REVIEWED " Needs usage of multiple ## in the macro " */
/*SAFETYMCUSW 76 S MR: 19.12 REVIEWED " Needs usage of multiple ## in the macro " */
#define PINMUX_SET(REG, BALLID, MUX)								\
			PINMUXREG->PINMMR##REG = (PINMUXREG->PINMMR##REG & PINMUX_BALL_##BALLID##_MASK) | (PINMUX_BALL_##BALLID##_##MUX)

/*SAFETYMCUSW 125 S MR: 19.13 REVIEWED " Needs usage of ## in the macro " */
/*SAFETYMCUSW 78 S MR: 19.10 REVIEWED " Macro parameter used for concatenation " */
#define PINMUX_GATE_EMIF_CLK_ENABLE(state)		\
			PINMUXREG->PINMMR29 = (PINMUXREG->PINMMR29 & PINMUX_GATE_EMIF_CLK_MASK) | (PINMUX_GATE_EMIF_CLK_##state)

/*SAFETYMCUSW 125 S MR: 19.13 REVIEWED " Needs usage of ## in the macro " */
/*SAFETYMCUSW 78 S MR: 19.10 REVIEWED " Macro parameter used for concatenation " */
#define PINMUX_GIOB_DISABLE_HET2_ENABLE(state)	\
			PINMUXREG->PINMMR29 = (PINMUXREG->PINMMR29 & PINMUX_GIOB_DISABLE_HET2_MASK) | (PINMUX_GIOB_DISABLE_HET2_##state)

/*SAFETYMCUSW 125 S MR: 19.13 REVIEWED " Needs usage of ## in the macro " */
/*SAFETYMCUSW 78 S MR: 19.10 REVIEWED " Macro parameter used for concatenation " */	
#define PINMUX_ALT_ADC_TRIGGER_SELECT(num)	\
			PINMUXREG->PINMMR30 = (PINMUXREG->PINMMR30 & PINMUX_ALT_ADC_TRIGGER_MASK) | (PINMUX_ALT_ADC_TRIGGER_##num)

/*SAFETYMCUSW 125 S MR: 19.13 REVIEWED " Needs usage of ## in the macro " */
/*SAFETYMCUSW 78 S MR: 19.10 REVIEWED " Macro parameter used for concatenation " */	
#define PINMUX_ETHERNET_SELECT(interface)	\
			PINMUXREG->PINMMR29 = (PINMUXREG->PINMMR29 & PINMUX_ETHERNET_MASK) | (PINMUX_ETHERNET_##interface)


void __init mux_init(void)
{
	/* Enable Pin Muxing */
	PINMUX_KICKER0 = 0x83E70B13U;
	PINMUX_KICKER1 = 0x95A4F1E0U;

    PINMUXREG->PINMMR0 = PINMUX_BALL_C3_MIBSPI3NCS_3 | PINMUX_BALL_B2_MIBSPI3NCS_2;
	
	PINMUXREG->PINMMR1 = PINMUX_BALL_E3_HET1_11 | PINMUX_BALL_E5_EMIF_DATA_4 | PINMUX_BALL_F5_EMIF_DATA_5;
	
	PINMUXREG->PINMMR2 = PINMUX_BALL_C1_GIOA_2 | PINMUX_BALL_G5_EMIF_DATA_6 | PINMUX_BALL_E1_GIOA_3 | PINMUX_BALL_B5_GIOA_5;
	
	PINMUXREG->PINMMR3 = PINMUX_BALL_K5_EMIF_DATA_7 | PINMUX_BALL_H3_GIOA_6 | PINMUX_BALL_L5_EMIF_DATA_8;
	
	PINMUXREG->PINMMR4 = PINMUX_BALL_M1_GIOA_7 | PINMUX_BALL_M5_EMIF_DATA_9 | PINMUX_BALL_V2_HET1_01 | PINMUX_BALL_U1_HET1_03;
	
	PINMUXREG->PINMMR5 = PINMUX_BALL_K18_HET1_0 | PINMUX_BALL_W5_HET1_02 | PINMUX_BALL_V6_HET1_05 | PINMUX_BALL_N5_EMIF_DATA_10;
	
	PINMUXREG->PINMMR6 = PINMUX_BALL_T1_HET1_07 | PINMUX_BALL_P5_EMIF_DATA_11 | PINMUX_BALL_V7_HET1_09 | PINMUX_BALL_R5_EMIF_DATA_12;
	
	PINMUXREG->PINMMR7 = PINMUX_BALL_R6_EMIF_DATA_13 | PINMUX_BALL_V5_MIBSPI3NCS_1 | PINMUX_BALL_W3_SCIRX | PINMUX_BALL_R7_EMIF_DATA_14;
	
	PINMUXREG->PINMMR8 = PINMUX_BALL_N2_SCITX | PINMUX_BALL_G3_MIBSPI1NCS_2 | PINMUX_BALL_N1_HET1_15 | PINMUX_BALL_R8_EMIF_DATA_15;
	
	PINMUXREG->PINMMR9 = ((~(PINMUXREG->PINMMR9 >> 18) & 0x00000001U ) << 18)| PINMUX_BALL_R9_ETMTRACECLKIN | PINMUX_BALL_W9_MIBSPI3NENA | PINMUX_BALL_V10_MIBSPI3NCS_0 | PINMUX_BALL_J3_MIBSPI1NCS_3;
	
	PINMUXREG->PINMMR10 = PINMUX_BALL_N19_AD1EVT | PINMUX_BALL_N15_EMIF_DATA_3 | PINMUX_BALL_N17_EMIF_nCS_0 | PINMUX_BALL_M15_EMIF_DATA_2;
	
	PINMUXREG->PINMMR11 = PINMUX_BALL_K17_EMIF_nCS_3 | PINMUX_BALL_M17_EMIF_nCS_4 | PINMUX_BALL_L15_EMIF_DATA_1 | PINMUX_BALL_P1_HET1_24;
	
	PINMUXREG->PINMMR12 = PINMUX_BALL_A14_HET1_26 | PINMUX_BALL_K15_EMIF_DATA_0 | PINMUX_BALL_G19_MIBSPI1NENA | PINMUX_BALL_H18_MIBSPI5NENA;
	
	PINMUXREG->PINMMR13 = PINMUX_BALL_J18_MIBSPI5SOMI_0 | PINMUX_BALL_J19_MIBSPI5SIMO_0 | PINMUX_BALL_H19_MIBSPI5CLK | PINMUX_BALL_R2_MIBSPI1NCS_0;
	
	PINMUXREG->PINMMR14 = PINMUX_BALL_E18_HET1_08 | PINMUX_BALL_K19_HET1_28 | PINMUX_BALL_D17_EMIF_nWE | PINMUX_BALL_D16_EMIF_BA_1;
	
	PINMUXREG->PINMMR15 = PINMUX_BALL_C17_EMIF_ADDR_21 | PINMUX_BALL_C16_EMIF_ADDR_20 | PINMUX_BALL_C15_EMIF_ADDR_19 | PINMUX_BALL_D15_EMIF_ADDR_18;
	
	PINMUXREG->PINMMR16 = PINMUX_BALL_E13_EMIF_BA_0 | PINMUX_BALL_C14_EMIF_ADDR_17 | PINMUX_BALL_D14_EMIF_ADDR_16 | PINMUX_BALL_E12_EMIF_nOE;
	
	PINMUXREG->PINMMR17 = PINMUX_BALL_D19_HET1_10 | PINMUX_BALL_E11_EMIF_nDQM_1 | PINMUX_BALL_B4_HET1_12 | PINMUX_BALL_E9_EMIF_ADDR_5;
	
	PINMUXREG->PINMMR18 = PINMUX_BALL_C13_EMIF_ADDR_15 | PINMUX_BALL_C12_EMIF_ADDR_14 | PINMUX_BALL_M2_GIOB_0;
	
	PINMUXREG->PINMMR19 = PINMUX_BALL_E8_EMIF_ADDR_4 | PINMUX_BALL_B11_HET1_30 | PINMUX_BALL_E10_EMIF_nDQM_0 | PINMUX_BALL_E7_EMIF_ADDR_3;
	
	PINMUXREG->PINMMR20 = PINMUX_BALL_C11_EMIF_ADDR_13 | PINMUX_BALL_C10_EMIF_ADDR_12 | PINMUX_BALL_F3_MIBSPI1NCS_1 | PINMUX_BALL_C9_EMIF_ADDR_11;
	
	PINMUXREG->PINMMR21 = PINMUX_BALL_D5_EMIF_ADDR_1 | PINMUX_BALL_C8_EMIF_ADDR_10 | PINMUX_BALL_C7_EMIF_ADDR_9;
	
	PINMUXREG->PINMMR22 = PINMUX_BALL_D4_EMIF_ADDR_0 | PINMUX_BALL_C5_EMIF_ADDR_7 | PINMUX_BALL_C4_EMIF_ADDR_6 | PINMUX_BALL_E6_EMIF_ADDR_2;
	
	PINMUXREG->PINMMR23 = ((~(PINMUXREG->PINMMR5 >> 1U) & 0x00000001U ) << 8U) | ((~(PINMUXREG->PINMMR5 >> 9U) & 0x00000001U ) << 16U) | ((~(PINMUXREG->PINMMR5 >> 17U) & 0x00000001U ) << 24U) | PINMUX_BALL_C6_EMIF_ADDR_8;
	
	PINMUXREG->PINMMR24 = ((~(PINMUXREG->PINMMR4 >> 17U) & 0x00000001U ) << 0U) | ((~(PINMUXREG->PINMMR4 >> 25U) & 0x00000001U ) << 8U) | ((~(PINMUXREG->PINMMR20 >> 17U) & 0x00000001U ) << 16U) | ((~(PINMUXREG->PINMMR8 >> 9U) & 0x00000001U ) << 24U);
	
	/*SAFETYMCUSW 134 S MR: 12.2 REVIEWED " Specific hardware use case " */
	PINMUXREG->PINMMR25 = ((~(PINMUXREG->PINMMR12 >> 17U) & 0x00000001U ) << 8U) | ((~(PINMUXREG->PINMMR7 >> 9U) & 0x00000001U ) << 16U) | ((~(PINMUXREG->PINMMR0 >> 26U) & 0x00000001U ) << 24U);
	
	/*SAFETYMCUSW 134 S MR: 12.2 REVIEWED " Specific hardware use case " */
	PINMUXREG->PINMMR26 = ((~(PINMUXREG->PINMMR0 >> 18U) & 0x00000001U ) << 0U) | ((~(PINMUXREG->PINMMR9 >> 10U) & 0x00000001U ) << 8U) | PINMUX_BALL_W6_MIBSPI5NCS_2 | PINMUX_BALL_T12_MIBSPI5NCS_3;
	
	PINMUXREG->PINMMR27 = PINMUX_BALL_E19_MIBSPI5NCS_0 | PINMUX_BALL_B6_MIBSPI5NCS_1 | PINMUX_BALL_E16_MIBSPI5SIMO_1 | PINMUX_BALL_H17_MIBSPI5SIMO_2;
	
	PINMUXREG->PINMMR28 = PINMUX_BALL_G17_MIBSPI5SIMO_3 | PINMUX_BALL_E17_MIBSPI5SOMI_1 | PINMUX_BALL_H16_MIBSPI5SOMI_2 | PINMUX_BALL_G16_MIBSPI5SOMI_3;
	
	PINMUXREG->PINMMR29 = PINMUX_BALL_D3_SPI2NENA;
	
	PINMUX_GATE_EMIF_CLK_ENABLE(OFF);
	PINMUX_GIOB_DISABLE_HET2_ENABLE(OFF);
	PINMUX_ALT_ADC_TRIGGER_SELECT(1);
	PINMUX_ETHERNET_SELECT(RMII);
	
	/*SAFETYMCUSW 120 S MR: 12.7 REVIEWED " Write reason " */	
	PINMUX_SET(0,A5,GIOA_0);                
	/*SAFETYMCUSW 120 S MR: 12.7 REVIEWED " Write reason " */	
	PINMUX_SET(18,A11,HET1_14);             
	/*SAFETYMCUSW 120 S MR: 12.7 REVIEWED " Write reason " */	
	PINMUX_SET(3,B3,HET1_22);               
	/*SAFETYMCUSW 120 S MR: 12.7 REVIEWED " Write reason " */	
	PINMUX_SET(1,C2,GIOA_1);                
	/*SAFETYMCUSW 120 S MR: 12.7 REVIEWED " Write reason " */	
	PINMUX_SET(21,K2,GIOB_1);               
	/*SAFETYMCUSW 120 S MR: 12.7 REVIEWED " Write reason " */	
	PINMUX_SET(0,W10,GIOB_3);
	
/* USER CODE BEGIN (3) */
	// FIXME: necessary to enable externa SDRAM
	PINMUX_GATE_EMIF_CLK_ENABLE(ON);
/* USER CODE END */
	
	/* Disable Pin Muxing */
	PINMUX_KICKER0 = 0x00000000U;
	PINMUX_KICKER1 = 0x00000000U;
}
