/* NOTE -- generated by scripts/ab_gen_iddefines.pl -- DO NOT EDIT */
/* ab_gen_iddefines.pl 2016-01-29 */

#ifndef __IDS_part2__
#define __IDS_part2__

#define CFG_PART_NAME	part2
#define CFG_PART_NAME_STR	"part2"
#define CFG_PART_ID	1
#define CFG_MAX_PRIO	200
#define CFG_PART_CPU	0
#define CFG_PART_TIMEPART	0
/* CFG_NUM_ERROR_RECORDS not defined */

#define CFG_TASK_main	0
#define CFG_TASK_main_PRIO	102
#define CFG_TASK_badTask1	1
#define CFG_TASK_badTask1_PRIO	150
#define CFG_TASK_badTask2	2
#define CFG_TASK_badTask2_PRIO	50
#define CFG_TASK_AccelerometerTask	3
#define CFG_TASK_AccelerometerTask_PRIO	100
#define CFG_TASK_ethTask	4
#define CFG_TASK_ethTask_PRIO	101
#define CFG_NUM_TASKS	5

#define CFG_ISR_ACC_IRQ	5
#define CFG_ISR_ACC_IRQ_PRIO	101
#define CFG_NUM_ISRS	1

#define CFG_HOOK__start	6
#define CFG_HOOK__start_PRIO	102
#define CFG_NUM_HOOKS	1

#define CFG_INIT_HOOK_ID	6
/* CFG_ERROR_HOOK_ID not defined */
/* CFG_EXCEPTION_HOOK_ID not defined */

#define CFG_NUM_INVOKABLES	0

#define CFG_NUM_RPCS	0

#define CFG_NUM_SHMS	0

#define CFG_KLDD_gpio_wr	0
#define CFG_KLDD_gpio_re	1
#define CFG_KLDD_gpio_toggle	2
#define CFG_KLDD_gpio_s	3
#define CFG_KLDD_gpio_res	4
#define CFG_NUM_KLDDS	5

#define CFG_NUM_IPEVS	0

#define CFG_NUM_COUNTERS	0

#define CFG_NUM_ALARMS	0

#define CFG_SCHEDTAB_test	0
#define CFG_SCHEDTAB_test_DURATION	100
#define CFG_NUM_SCHEDTABS	1

#define CFG_NUM_WQS	0


#endif
