/* config.c -- AUTOGENERATED -- DO NOT EDIT -- */
/* ab_gen_config_c.pl 2016-01-29 */

/* WARNING: THIS FILE LACKS THE FINAL RELOCATION INFORMATION */
/* WARNING: rerun ab_gen_config_c.pl with -r for the final relocation pass */

#include <kernel.h>
#include <assert.h>
#include <sched_state.h>
#include <core_state.h>
#include <part_state.h>
#include <task_state.h>
#include <kldd_state.h>
#include <ipev_state.h>
#include <counter_state.h>
#include <alarm_state.h>
#include <schedtab_state.h>
#include <isr_state.h>
#include <wq_state.h>
#include <shm_state.h>
#include <arch_mpu_state.h>
#include <ipi_state.h>
#include <tp_state.h>
#include <hm_state.h>
#include <hv_error.h>
#include <rpc_state.h>

/* forward declaration */
extern struct task task_dyn_idle_0[];
extern struct task task_dyn_part_1[];
extern struct alarm alarm_dyn_part_1[];
extern struct schedtab schedtab_dyn_part_1[];
extern struct wq wq_dyn_part_1[];
extern struct rpc rpc_dyn_part_1[];
extern struct task task_dyn_part_2[];
extern struct alarm alarm_dyn_part_2[];
extern struct schedtab schedtab_dyn_part_2[];
extern struct wq wq_dyn_part_2[];
extern struct rpc rpc_dyn_part_2[];
extern struct arch_reg_frame kernel_reg_frames_core_0[];
extern struct arch_fpu_frame kernel_fpu_frames_core_0[];
extern struct arch_ctxt_frame kernel_ctxt_frames_core_0[];
extern const struct wq_cfg wq_cfg[];
extern const struct counter_access counter_access[];
extern const struct shm_access shm_access[];
extern const struct shm_cfg shm_cfg[];
extern const struct kldd_cfg kldd_cfg[];
extern const struct ipev_cfg ipev_cfg[];
extern const struct arch_mpu_task_cfg mpu_task_cfg[];
extern const struct arch_mpu_part_cfg mpu_part_cfg[];
extern const struct tpwindow_cfg tpwindow_cfg[];
extern const struct rpc_cfg rpc_cfg[];

/* scheduler configuration */
const uint8_t num_cpus __section_cfg = 1;
const uint8_t num_timeparts __section_cfg = 3;
struct sched_state sched_state_core_0 __section_sched_state_core(0);
struct timepart_state timepart_states_core_0[3] __section_bss_core(0);
struct core_state core_state_core_0 __section_bss_core(0);
/* kernel stacks per CPU for ISRs and exceptions */
unsigned char kern_stack_core_0[1536] __aligned(ARCH_KERN_STACK_ALIGN) __section_kern_stack_core(0);
unsigned char nmi_stack_core_0[256] __aligned(ARCH_KERN_STACK_ALIGN) __section_nmi_stack_core(0);
unsigned char idle_stack_core_0[256] __aligned(ARCH_KERN_STACK_ALIGN) __section_stack_core(0);

/* per-CPU kernel register contexts */
struct arch_ctxt_frame kern_ctxts_core_0[12] __section_context_core(0);
struct arch_ctxt_frame nmi_ctxts_core_0[8] __section_context_core(0);
struct arch_ctxt_frame idle_ctxts_core_0[4] __section_context_core(0);

/* per-CPU configuration */
const struct core_cfg core_cfg[1] = {
	/* CPU 0 */ {
		.sched = &sched_state_core_0,
		.timeparts = timepart_states_core_0,
		.core_state = &core_state_core_0,
		.kern_stack = kern_stack_core_0,
		.nmi_stack =  nmi_stack_core_0,
		.idle_stack = idle_stack_core_0,
		.kern_ctxts = kern_ctxts_core_0,
		.nmi_ctxts =  nmi_ctxts_core_0,
		.idle_ctxts = idle_ctxts_core_0,
	},
};

const size_t kern_stack_size = 1536;
const size_t nmi_stack_size = 256;
const size_t idle_stack_size = 256;
const uint8_t kern_num_ctxts = 12;
const uint8_t nmi_num_ctxts = 8;
const uint8_t idle_num_ctxts = 4;

/* idle partition scheduling state */
user_sched_state_t idle_user_sched_state_core_0 __section_bss_core(0);

/* partition configuration */
const uint8_t num_partitions __section_cfg = 3;
struct part part_dyn_idle_0 __section_bss_core(0);
struct part part_dyn_part_0 __section_bss_core(0);
struct part part_dyn_part_1 __section_bss_core(0);
const struct part_cfg part_cfg[3] = {
	/* idle partition on CPU 0 */ {
		.part = &part_dyn_idle_0,
		.cpu_id = 0,
		.tp_id = 0,
		.user_sched_state = &idle_user_sched_state_core_0,
		.user_error_state = NULL, /* not used */
		.user_exception_state = NULL, /* not used */

		.name = "idle part 0", /* empty name */
		.tasks = task_dyn_idle_0,
		.init_hook_id = 0,
		.error_hook_id = 0xffff, /* not used */
		.exception_hook_id = 0xffff, /* not used */
		.num_error_states = 0, /* not used */
		.num_tasks = 1,
		.mpu_part_cfg = &mpu_part_cfg[0],
		.part_id = 0,
		.flags = 0,
		.initial_operating_mode = PART_OPERATING_MODE_NORMAL,
	},
	/* partition 'part1' on CPU 0 */ {
		.part = &part_dyn_part_0,
		.cpu_id = 0,
		.tp_id = 0,
		.period = 100000000,
		.duration = 100000000,
		.user_sched_state = (user_sched_state_t *)0x00000000, /* NULL */
		.user_error_state = (user_error_state_t *)0x00000000, /* NULL */
		.user_exception_state = (user_exception_state_t *)0x00000000, /* NULL */

		.tasks = task_dyn_part_1,
		.num_tasks = 12,
		.mpu_part_cfg = &mpu_part_cfg[1],
		.kldds = &kldd_cfg[0],
		.num_kldds = 5,
		.ipevs = &ipev_cfg[0],
		.num_ipevs = 0,
		.ctr_accs = &counter_access[0],
		.num_ctr_accs = 0,
		.alarms = alarm_dyn_part_1,
		.num_alarms = 0,
		.schedtabs = schedtab_dyn_part_1,
		.num_schedtabs = 1,
		.wq_cfgs = &wq_cfg[0],
		.wqs = wq_dyn_part_1,
		.num_wqs = 0,
		.shm_accs = &shm_access[0],
		.num_shm_accs = 0,
		.rpcs = &rpc_cfg[0],
		.num_rpcs = 0,
		.init_hook_id = 11,
		.error_hook_id = 0xffff, /* not used */
		.num_error_states = 0, /* not used */
		.exception_hook_id = 0xffff, /* not used */
		.max_prio = 200,
		.name = "part1",
		.part_id = 1,
		.flags = PART_FLAG_RESTARTABLE,
		.initial_operating_mode = PART_OPERATING_MODE_COLD_START,
		.sda1_base = 0x00000000, /* NULL */
		.sda2_base = 0x00000000, /* NULL */
	},
	/* partition 'part2' on CPU 0 */ {
		.part = &part_dyn_part_1,
		.cpu_id = 0,
		.tp_id = 0,
		.period = 100000000,
		.duration = 100000000,
		.user_sched_state = (user_sched_state_t *)0x00000000, /* NULL */
		.user_error_state = (user_error_state_t *)0x00000000, /* NULL */
		.user_exception_state = (user_exception_state_t *)0x00000000, /* NULL */

		.tasks = task_dyn_part_2,
		.num_tasks = 7,
		.mpu_part_cfg = &mpu_part_cfg[2],
		.kldds = &kldd_cfg[5],
		.num_kldds = 5,
		.ipevs = &ipev_cfg[0],
		.num_ipevs = 0,
		.ctr_accs = &counter_access[0],
		.num_ctr_accs = 0,
		.alarms = alarm_dyn_part_2,
		.num_alarms = 0,
		.schedtabs = schedtab_dyn_part_2,
		.num_schedtabs = 1,
		.wq_cfgs = &wq_cfg[0],
		.wqs = wq_dyn_part_2,
		.num_wqs = 0,
		.shm_accs = &shm_access[0],
		.num_shm_accs = 0,
		.rpcs = &rpc_cfg[0],
		.num_rpcs = 0,
		.init_hook_id = 6,
		.error_hook_id = 0xffff, /* not used */
		.num_error_states = 0, /* not used */
		.exception_hook_id = 0xffff, /* not used */
		.max_prio = 200,
		.name = "part2",
		.part_id = 2,
		.flags = PART_FLAG_RESTARTABLE,
		.initial_operating_mode = PART_OPERATING_MODE_COLD_START,
		.sda1_base = 0x00000000, /* NULL */
		.sda2_base = 0x00000000, /* NULL */
	},
};

/* task configuration */
const uint16_t num_tasks __section_cfg = 20;
const struct task_cfg task_cfg[20] = {
	/* idle task on CPU 0 */ {
		.task = &task_dyn_idle_0[0],
		.name = "idle task 0",
		.task_id = 0,
		.cpu_id = 0,
		.part_cfg = &part_cfg[0],
		.timepart = &timepart_states_core_0[0],
		.base_prio = 0,
		.elev_prio = 0, /* not used */
		.regs = &kernel_reg_frames_core_0[0],
		.fpu = NULL, /* not used */
		.ctxt = &kernel_ctxt_frames_core_0[0],
		.num_ctxts = 4,
		.mpu_task_cfg = &mpu_task_cfg[0],
		.irq = 0, /* not used */
		.max_activations = 1, /* not used */
		.cfgflags_type = TASK_TYPE_HOOK,
	},
	/* #1: blocking task 'main' in partition 'part1' */ {
		.task = &task_dyn_part_1[0],
		.name = "main",
		.task_id = 0,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.period = -1,
		.capacity = -1,

		.base_prio = 102,
		.elev_prio = 102,
		.regs = &kernel_reg_frames_core_0[1],
		.fpu = &kernel_fpu_frames_core_0[0],
		.ctxt = &kernel_ctxt_frames_core_0[4],
		.num_ctxts = 8,
		.mpu_task_cfg = &mpu_task_cfg[1],
		.irq = 0, /* not used */
		.max_activations = 1,

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_TASK | TASK_CFGFLAG_ACTIVATABLE | TASK_CFGFLAG_MAYBLOCK,
	},
	/* #2: task 'SteeringTask' in partition 'part1' */ {
		.task = &task_dyn_part_1[1],
		.name = "SteeringTask",
		.task_id = 1,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.period = -1,
		.capacity = -1,

		.base_prio = 104,
		.elev_prio = 104,
		.regs = &kernel_reg_frames_core_0[2],
		.fpu = &kernel_fpu_frames_core_0[1],
		.ctxt = &kernel_ctxt_frames_core_0[12],
		.num_ctxts = 8,
		.mpu_task_cfg = &mpu_task_cfg[2],
		.irq = 0, /* not used */
		.max_activations = 10,

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_TASK | TASK_CFGFLAG_ACTIVATABLE,
	},
	/* #3: task 'PWRTrainTask' in partition 'part1' */ {
		.task = &task_dyn_part_1[2],
		.name = "PWRTrainTask",
		.task_id = 2,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.period = -1,
		.capacity = -1,

		.base_prio = 103,
		.elev_prio = 103,
		.regs = &kernel_reg_frames_core_0[3],
		.fpu = &kernel_fpu_frames_core_0[2],
		.ctxt = &kernel_ctxt_frames_core_0[20],
		.num_ctxts = 8,
		.mpu_task_cfg = &mpu_task_cfg[3],
		.irq = 0, /* not used */
		.max_activations = 10,

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_TASK | TASK_CFGFLAG_ACTIVATABLE,
	},
	/* #4: ISR 'VR_IRQ' in partition 'part1' */ {
		.task = &task_dyn_part_1[3],
		.name = "VR_IRQ",
		.task_id = 3,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.base_prio = 109,
		.elev_prio = 109, /* not used */
		.regs = &kernel_reg_frames_core_0[4],
		.fpu = &kernel_fpu_frames_core_0[3],
		.ctxt = &kernel_ctxt_frames_core_0[28],
		.num_ctxts = 5,
		.mpu_task_cfg = &mpu_task_cfg[4],
		.irq = 9,
		.max_activations = 1, /* not used */

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_ISR | TASK_CFGFLAG_ACTIVATABLE | TASK_CFGFLAG_ISR_UNMASK,
	},
	/* #5: ISR 'VL_IRQ' in partition 'part1' */ {
		.task = &task_dyn_part_1[4],
		.name = "VL_IRQ",
		.task_id = 4,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.base_prio = 107,
		.elev_prio = 107, /* not used */
		.regs = &kernel_reg_frames_core_0[5],
		.fpu = &kernel_fpu_frames_core_0[4],
		.ctxt = &kernel_ctxt_frames_core_0[33],
		.num_ctxts = 5,
		.mpu_task_cfg = &mpu_task_cfg[5],
		.irq = 7,
		.max_activations = 1, /* not used */

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_ISR | TASK_CFGFLAG_ACTIVATABLE | TASK_CFGFLAG_ISR_UNMASK,
	},
	/* #6: ISR 'HR_IRQ' in partition 'part1' */ {
		.task = &task_dyn_part_1[5],
		.name = "HR_IRQ",
		.task_id = 5,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.base_prio = 110,
		.elev_prio = 110, /* not used */
		.regs = &kernel_reg_frames_core_0[6],
		.fpu = &kernel_fpu_frames_core_0[5],
		.ctxt = &kernel_ctxt_frames_core_0[38],
		.num_ctxts = 5,
		.mpu_task_cfg = &mpu_task_cfg[6],
		.irq = 23,
		.max_activations = 1, /* not used */

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_ISR | TASK_CFGFLAG_ACTIVATABLE | TASK_CFGFLAG_ISR_UNMASK,
	},
	/* #7: ISR 'HL_IRQ' in partition 'part1' */ {
		.task = &task_dyn_part_1[6],
		.name = "HL_IRQ",
		.task_id = 6,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.base_prio = 108,
		.elev_prio = 108, /* not used */
		.regs = &kernel_reg_frames_core_0[7],
		.fpu = &kernel_fpu_frames_core_0[6],
		.ctxt = &kernel_ctxt_frames_core_0[43],
		.num_ctxts = 5,
		.mpu_task_cfg = &mpu_task_cfg[7],
		.irq = 8,
		.max_activations = 1, /* not used */

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_ISR | TASK_CFGFLAG_ACTIVATABLE | TASK_CFGFLAG_ISR_UNMASK,
	},
	/* #8: ISR 'PWR_IRQ' in partition 'part1' */ {
		.task = &task_dyn_part_1[7],
		.name = "PWR_IRQ",
		.task_id = 7,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.base_prio = 112,
		.elev_prio = 112, /* not used */
		.regs = &kernel_reg_frames_core_0[8],
		.fpu = &kernel_fpu_frames_core_0[7],
		.ctxt = &kernel_ctxt_frames_core_0[48],
		.num_ctxts = 5,
		.mpu_task_cfg = &mpu_task_cfg[8],
		.irq = 28,
		.max_activations = 1, /* not used */

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_ISR | TASK_CFGFLAG_ACTIVATABLE | TASK_CFGFLAG_ISR_UNMASK,
	},
	/* #9: ISR 'STR_IRQ' in partition 'part1' */ {
		.task = &task_dyn_part_1[8],
		.name = "STR_IRQ",
		.task_id = 8,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.base_prio = 113,
		.elev_prio = 113, /* not used */
		.regs = &kernel_reg_frames_core_0[9],
		.fpu = &kernel_fpu_frames_core_0[8],
		.ctxt = &kernel_ctxt_frames_core_0[53],
		.num_ctxts = 5,
		.mpu_task_cfg = &mpu_task_cfg[9],
		.irq = 29,
		.max_activations = 1, /* not used */

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_ISR | TASK_CFGFLAG_ACTIVATABLE | TASK_CFGFLAG_ISR_UNMASK,
	},
	/* #10: ISR 'DIS_IRQ' in partition 'part1' */ {
		.task = &task_dyn_part_1[9],
		.name = "DIS_IRQ",
		.task_id = 9,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.base_prio = 120,
		.elev_prio = 120, /* not used */
		.regs = &kernel_reg_frames_core_0[10],
		.fpu = NULL, /* not used */
		.ctxt = &kernel_ctxt_frames_core_0[58],
		.num_ctxts = 5,
		.mpu_task_cfg = &mpu_task_cfg[10],
		.irq = 40,
		.max_activations = 1, /* not used */

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_ISR | TASK_CFGFLAG_ACTIVATABLE | TASK_CFGFLAG_ISR_UNMASK,
	},
	/* #11: ISR 'ULTR_IRQ' in partition 'part1' */ {
		.task = &task_dyn_part_1[10],
		.name = "ULTR_IRQ",
		.task_id = 10,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.base_prio = 111,
		.elev_prio = 111, /* not used */
		.regs = &kernel_reg_frames_core_0[11],
		.fpu = NULL, /* not used */
		.ctxt = &kernel_ctxt_frames_core_0[63],
		.num_ctxts = 5,
		.mpu_task_cfg = &mpu_task_cfg[11],
		.irq = 27,
		.max_activations = 1, /* not used */

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_ISR | TASK_CFGFLAG_ACTIVATABLE | TASK_CFGFLAG_ISR_UNMASK,
	},
	/* #12: Hook '_start' in partition 'part1' */ {
		.task = &task_dyn_part_1[11],
		.name = "_start",
		.task_id = 11,
		.cpu_id = 0,
		.part_cfg = &part_cfg[1],
		.timepart = &timepart_states_core_0[0],

		.base_prio = 102,
		.elev_prio = 102, /* not used */
		.regs = &kernel_reg_frames_core_0[12],
		.fpu = NULL, /* not used */
		.ctxt = &kernel_ctxt_frames_core_0[68],
		.num_ctxts = 5,
		.mpu_task_cfg = &mpu_task_cfg[12],
		.irq = 0, /* not used */
		.max_activations = 1, /* not used */

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_HOOK | TASK_CFGFLAG_ACTIVATABLE,
	},
	/* #13: blocking task 'main' in partition 'part2' */ {
		.task = &task_dyn_part_2[0],
		.name = "main",
		.task_id = 0,
		.cpu_id = 0,
		.part_cfg = &part_cfg[2],
		.timepart = &timepart_states_core_0[0],

		.period = -1,
		.capacity = -1,

		.base_prio = 102,
		.elev_prio = 102,
		.regs = &kernel_reg_frames_core_0[13],
		.fpu = NULL, /* not used */
		.ctxt = &kernel_ctxt_frames_core_0[73],
		.num_ctxts = 8,
		.mpu_task_cfg = &mpu_task_cfg[13],
		.irq = 0, /* not used */
		.max_activations = 1,

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_TASK | TASK_CFGFLAG_ACTIVATABLE | TASK_CFGFLAG_MAYBLOCK,
	},
	/* #14: task 'badTask1' in partition 'part2' */ {
		.task = &task_dyn_part_2[1],
		.name = "badTask1",
		.task_id = 1,
		.cpu_id = 0,
		.part_cfg = &part_cfg[2],
		.timepart = &timepart_states_core_0[0],

		.period = -1,
		.capacity = -1,

		.base_prio = 150,
		.elev_prio = 150,
		.regs = &kernel_reg_frames_core_0[14],
		.fpu = &kernel_fpu_frames_core_0[9],
		.ctxt = &kernel_ctxt_frames_core_0[81],
		.num_ctxts = 8,
		.mpu_task_cfg = &mpu_task_cfg[14],
		.irq = 0, /* not used */
		.max_activations = 10,

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_TASK | TASK_CFGFLAG_ACTIVATABLE,
	},
	/* #15: task 'badTask2' in partition 'part2' */ {
		.task = &task_dyn_part_2[2],
		.name = "badTask2",
		.task_id = 2,
		.cpu_id = 0,
		.part_cfg = &part_cfg[2],
		.timepart = &timepart_states_core_0[0],

		.period = -1,
		.capacity = -1,

		.base_prio = 50,
		.elev_prio = 50,
		.regs = &kernel_reg_frames_core_0[15],
		.fpu = &kernel_fpu_frames_core_0[10],
		.ctxt = &kernel_ctxt_frames_core_0[89],
		.num_ctxts = 8,
		.mpu_task_cfg = &mpu_task_cfg[15],
		.irq = 0, /* not used */
		.max_activations = 10,

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_TASK | TASK_CFGFLAG_ACTIVATABLE,
	},
	/* #16: task 'AccelerometerTask' in partition 'part2' */ {
		.task = &task_dyn_part_2[3],
		.name = "AccelerometerTask",
		.task_id = 3,
		.cpu_id = 0,
		.part_cfg = &part_cfg[2],
		.timepart = &timepart_states_core_0[0],

		.period = -1,
		.capacity = -1,

		.base_prio = 100,
		.elev_prio = 100,
		.regs = &kernel_reg_frames_core_0[16],
		.fpu = NULL, /* not used */
		.ctxt = &kernel_ctxt_frames_core_0[97],
		.num_ctxts = 8,
		.mpu_task_cfg = &mpu_task_cfg[16],
		.irq = 0, /* not used */
		.max_activations = 10,

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_TASK | TASK_CFGFLAG_ACTIVATABLE,
	},
	/* #17: task 'ethTask' in partition 'part2' */ {
		.task = &task_dyn_part_2[4],
		.name = "ethTask",
		.task_id = 4,
		.cpu_id = 0,
		.part_cfg = &part_cfg[2],
		.timepart = &timepart_states_core_0[0],

		.period = -1,
		.capacity = -1,

		.base_prio = 101,
		.elev_prio = 101,
		.regs = &kernel_reg_frames_core_0[17],
		.fpu = NULL, /* not used */
		.ctxt = &kernel_ctxt_frames_core_0[105],
		.num_ctxts = 8,
		.mpu_task_cfg = &mpu_task_cfg[17],
		.irq = 0, /* not used */
		.max_activations = 10,

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_TASK | TASK_CFGFLAG_ACTIVATABLE,
	},
	/* #18: ISR 'ACC_IRQ' in partition 'part2' */ {
		.task = &task_dyn_part_2[5],
		.name = "ACC_IRQ",
		.task_id = 5,
		.cpu_id = 0,
		.part_cfg = &part_cfg[2],
		.timepart = &timepart_states_core_0[0],

		.base_prio = 101,
		.elev_prio = 101, /* not used */
		.regs = &kernel_reg_frames_core_0[18],
		.fpu = &kernel_fpu_frames_core_0[11],
		.ctxt = &kernel_ctxt_frames_core_0[113],
		.num_ctxts = 5,
		.mpu_task_cfg = &mpu_task_cfg[18],
		.irq = 6,
		.max_activations = 1, /* not used */

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_ISR | TASK_CFGFLAG_ACTIVATABLE | TASK_CFGFLAG_ISR_UNMASK,
	},
	/* #19: Hook '_start' in partition 'part2' */ {
		.task = &task_dyn_part_2[6],
		.name = "_start",
		.task_id = 6,
		.cpu_id = 0,
		.part_cfg = &part_cfg[2],
		.timepart = &timepart_states_core_0[0],

		.base_prio = 102,
		.elev_prio = 102, /* not used */
		.regs = &kernel_reg_frames_core_0[19],
		.fpu = NULL, /* not used */
		.ctxt = &kernel_ctxt_frames_core_0[118],
		.num_ctxts = 5,
		.mpu_task_cfg = &mpu_task_cfg[19],
		.irq = 0, /* not used */
		.max_activations = 1, /* not used */

		.entry = 0x00000000, /* NULL */
		.stack = 0x00000000, /* NULL */
		.stack_size = 0x00000000,
		.arg0  = 0x00000000, /* NULL */

		.cfgflags_type = TASK_TYPE_HOOK | TASK_CFGFLAG_ACTIVATABLE,
	},
};
struct task task_dyn_idle_0[1] __section_bss_core(0);
struct task task_dyn_part_1[12] __section_bss_core(0);
struct task task_dyn_part_2[7] __section_bss_core(0);

/* registers contexts (one for each partition + shared regs for tasks) */
struct arch_reg_frame kernel_reg_frames_core_0[20] __section_reg_core(0);

/* FPU contexts (tasks can disable or share FPU registers) */
struct arch_fpu_frame kernel_fpu_frames_core_0[12] __section_reg_core(0);

/* Hardware registers contexts (variable per task) */
struct arch_ctxt_frame kernel_ctxt_frames_core_0[123] __section_context_core(0);

/* KLDD calltables */
const struct kldd_cfg kldd_cfg[10] = {
	/* kldd '0' in partition 'part1' */ {
		.func = (void*)0x00000000, /* bsp_kldd_gpio_write */
		.arg0 = (void*)0x00000000, /*  */
	},
	/* kldd '0' in partition 'part1' */ {
		.func = (void*)0x00000000, /* bsp_kldd_gpio_read */
		.arg0 = (void*)0x00000000, /*  */
	},
	/* kldd '0' in partition 'part1' */ {
		.func = (void*)0x00000000, /* bsp_kldd_gpio_pin_toggle */
		.arg0 = (void*)0x00000000, /*  */
	},
	/* kldd '0' in partition 'part1' */ {
		.func = (void*)0x00000000, /* bsp_kldd_gpio_set */
		.arg0 = (void*)0x00000000, /*  */
	},
	/* kldd '0' in partition 'part1' */ {
		.func = (void*)0x00000000, /* bsp_kldd_gpio_reset */
		.arg0 = (void*)0x00000000, /*  */
	},
	/* kldd '0' in partition 'part2' */ {
		.func = (void*)0x00000000, /* bsp_kldd_gpio_write */
		.arg0 = (void*)0x00000000, /*  */
	},
	/* kldd '0' in partition 'part2' */ {
		.func = (void*)0x00000000, /* bsp_kldd_gpio_read */
		.arg0 = (void*)0x00000000, /*  */
	},
	/* kldd '0' in partition 'part2' */ {
		.func = (void*)0x00000000, /* bsp_kldd_gpio_pin_toggle */
		.arg0 = (void*)0x00000000, /*  */
	},
	/* kldd '0' in partition 'part2' */ {
		.func = (void*)0x00000000, /* bsp_kldd_gpio_set */
		.arg0 = (void*)0x00000000, /*  */
	},
	/* kldd '0' in partition 'part2' */ {
		.func = (void*)0x00000000, /* bsp_kldd_gpio_reset */
		.arg0 = (void*)0x00000000, /*  */
	},
};

/* IPEV table */
const struct ipev_cfg ipev_cfg[0] = {
};

/* global counter table */
const uint8_t num_counters __section_cfg = 2;
struct counter counter_dyn_0 __section_bss_core(0);
struct counter counter_dyn_1 __section_bss_core(0);
const struct counter_cfg counter_cfg[2] = {
	/* counter 0 'SystemTimer' */ {
		.counter = &counter_dyn_0,
		.maxallowedvalue = 4294967295,
		.ticksperbase = 1,
		.mincycle = 1,
		.type = COUNTER_TYPE_HW,
		.cpu_id = 0,
	},
	/* counter 1 'mycounter1' */ {
		.counter = &counter_dyn_1,
		.maxallowedvalue = 255,
		.ticksperbase = 10,
		.mincycle = 1,
		.type = COUNTER_TYPE_SW,
		.cpu_id = 0,
	},
};

/* partition counter access table */
const struct counter_access counter_access[0] = {
};

/* alarm table */
const struct alarm_cfg alarm_cfg[2] = {
	/* partition 'part1' sched_table 'car' */ {
		.counter_id = 0, /* SystemTimer */
		.cpu_id = 0,
		.action = ALARM_ACTION_SCHEDTAB,
		.u.schedtab = &schedtab_dyn_part_1[0],
	},
	/* partition 'part2' sched_table 'test' */ {
		.counter_id = 0, /* SystemTimer */
		.cpu_id = 0,
		.action = ALARM_ACTION_SCHEDTAB,
		.u.schedtab = &schedtab_dyn_part_2[0],
	},
};
struct alarm alarm_dyn_part_1[0] __section_bss_core(0);
struct alarm alarm_dyn_part_2[0] __section_bss_core(0);

struct alarm alarm_dyn_schedtab_0 __section_bss_core(0);
struct alarm alarm_dyn_schedtab_1 __section_bss_core(0);

/* sched_table table */
const uint8_t num_schedtabs __section_cfg = 2;
const struct schedtab_cfg schedtab_cfg[2] = {
	/* partition 'part1' sched_table 0 'car' */ {
		.counter_id = 0, /* SystemTimer */
		.flags = 0 | SCHEDTAB_FLAG_REPEATING,
		.duration = 6,
		.alarm = &alarm_dyn_schedtab_0,
		.start_idx = 0,
	},
	/* partition 'part2' sched_table 0 'test' */ {
		.counter_id = 0, /* SystemTimer */
		.flags = 0 | SCHEDTAB_FLAG_REPEATING,
		.duration = 100,
		.precision = 0,
		.alarm = &alarm_dyn_schedtab_1,
		.start_idx = 6,
	},
};
struct schedtab schedtab_dyn_part_1[1] __section_bss_core(0);
struct schedtab schedtab_dyn_part_2[1] __section_bss_core(0);

/* schedtab_action table */
const struct schedtab_action_cfg schedtab_action_cfg[12] = {
	/* #0: schedule table 'car' */ {
		.action = SCHEDTAB_ACTION_START,
	},
	/* #1: offset 3 */ {
		.action = SCHEDTAB_ACTION_WAIT,
		.u.time = 3,
	},
	{
		.action = SCHEDTAB_ACTION_TASK,
		.u.task = &task_dyn_part_1[1] /* partition 'part1' task 'SteeringTask' */,
	},
	/* #3: offset 6 */ {
		.action = SCHEDTAB_ACTION_WAIT,
		.u.time = 3,
	},
	{
		.action = SCHEDTAB_ACTION_TASK,
		.u.task = &task_dyn_part_1[2] /* partition 'part1' task 'PWRTrainTask' */,
	},
	/* #5: wrap around to 0 */ {
		.action = SCHEDTAB_ACTION_WRAP,
		.next_idx = 0,
	},
	/* #6: schedule table 'test' */ {
		.action = SCHEDTAB_ACTION_START,
	},
	/* #7: offset 50 */ {
		.action = SCHEDTAB_ACTION_WAIT,
		.u.time = 50,
	},
	{
		.action = SCHEDTAB_ACTION_TASK,
		.u.task = &task_dyn_part_2[1] /* partition 'part2' task 'badTask1' */,
	},
	/* #9: offset 100 */ {
		.action = SCHEDTAB_ACTION_WAIT,
		.u.time = 50,
	},
	{
		.action = SCHEDTAB_ACTION_TASK,
		.u.task = &task_dyn_part_2[3] /* partition 'part2' task 'AccelerometerTask' */,
	},
	/* #11: wrap around to 6 */ {
		.action = SCHEDTAB_ACTION_WRAP,
		.next_idx = 6,
	},
};

/* ISR call table */
const struct isr_cfg isr_cfg[82] = {
	/* ISR 0 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 1 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 2 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 3 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 4 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 5 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 6 */ {
		.func = kernel_wake_isr_task,
		.arg0 = &task_cfg[18], /* user ISR */
	},
	/* ISR 7 */ {
		.func = kernel_wake_isr_task,
		.arg0 = &task_cfg[5], /* user ISR */
	},
	/* ISR 8 */ {
		.func = kernel_wake_isr_task,
		.arg0 = &task_cfg[7], /* user ISR */
	},
	/* ISR 9 */ {
		.func = kernel_wake_isr_task,
		.arg0 = &task_cfg[4], /* user ISR */
	},
	/* ISR 10 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 11 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 12 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 13 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 14 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 15 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 16 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 17 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 18 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 19 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 20 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 21 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 22 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 23 */ {
		.func = kernel_wake_isr_task,
		.arg0 = &task_cfg[6], /* user ISR */
	},
	/* ISR 24 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 25 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 26 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 27 */ {
		.func = kernel_wake_isr_task,
		.arg0 = &task_cfg[11], /* user ISR */
	},
	/* ISR 28 */ {
		.func = kernel_wake_isr_task,
		.arg0 = &task_cfg[8], /* user ISR */
	},
	/* ISR 29 */ {
		.func = kernel_wake_isr_task,
		.arg0 = &task_cfg[9], /* user ISR */
	},
	/* ISR 30 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 31 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 32 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 33 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 34 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 35 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 36 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 37 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 38 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 39 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 40 */ {
		.func = kernel_wake_isr_task,
		.arg0 = &task_cfg[10], /* user ISR */
	},
	/* ISR 41 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 42 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 43 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 44 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 45 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 46 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 47 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 48 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 49 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 50 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 51 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 52 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 53 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 54 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 55 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 56 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 57 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 58 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 59 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 60 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 61 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 62 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 63 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 64 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 65 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 66 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 67 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 68 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 69 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 70 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 71 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 72 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 73 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 74 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 75 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 76 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 77 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 78 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 79 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 80 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
	/* ISR 81 */ {
		.func = (void*)0x00000000, /* NULL */
		.arg0 = (void*)0x00000000, /* NULL */
	},
};

/* Wait queue table */
const struct wq_cfg wq_cfg[0] = {
};
struct wq wq_dyn_part_1[0] __section_bss_core(0);
struct wq wq_dyn_part_2[0] __section_bss_core(0);

struct rpc rpc_dyn_part_1[0] __section_bss_core(0);
struct rpc rpc_dyn_part_2[0] __section_bss_core(0);

/* SHM table */
/* const struct shm_cfg shm_cfg[] is emitted by MPU generator */
const struct shm_access shm_access[0] = {
};

/* RPC table */
const struct rpc_cfg rpc_cfg[0] = {
};

/** cross-core IPI jobs (num_actions x (num_cpus-1) x num_cpus) */
const uint8_t num_ipi_actions __section_cfg = 0;
struct ipi_action ipi_actions_core_0[0] __section_context_core(0);

/** per-core IPI state */
struct ipi_state ipi_state_core_0 __section_context_core(0);

/** per-CPU IPI configuration */
const struct ipi_cfg ipi_cfg[1] = {
	/* CPU 0 */ {
		.state = &ipi_state_core_0,
		.actions = {
			NULL, /* no IPIs to self */
		},
	},
};
/* Time partition schedule tables */
const uint8_t num_tpschedules __section_cfg = 1;
const struct tpschedule_cfg tpschedule_cfg[1] = {
	/* default schedule */ {
	.start = &tpwindow_cfg[0],
	},
};

const struct tpwindow_cfg tpwindow_cfg[1] = {
	/* default window */ {
		.timepart = 0,
		.duration = 100000000,
		.flags = TPWINDOW_FLAG_FIRST | TPWINDOW_FLAG_LAST,
	},
};

/* System HM tables */
const uint8_t num_hm_tables __section_cfg = 1;
const struct hm_table hm_table_system_cfg[1] = {
	/* system HM table 0 'default' */ { .level_action_error_code = {
		HM_ACTION_DEFAULT_SYSTEM_0, /* default */
		HM_ACTION_DEFAULT_SYSTEM_1, /* default */
		HM_ACTION_DEFAULT_SYSTEM_2, /* default */
		HM_ACTION_DEFAULT_SYSTEM_3, /* default */
		HM_ACTION_DEFAULT_SYSTEM_4, /* default */
		HM_ACTION_DEFAULT_SYSTEM_5, /* default */
		HM_ACTION_DEFAULT_SYSTEM_6, /* default */
		HM_ACTION_DEFAULT_SYSTEM_7, /* default */
		HM_ACTION_DEFAULT_SYSTEM_8, /* default */
		HM_ACTION_DEFAULT_SYSTEM_9, /* default */
		HM_ACTION_DEFAULT_SYSTEM_10, /* default */
		HM_ACTION_DEFAULT_SYSTEM_11, /* default */
		HM_ACTION_DEFAULT_SYSTEM_12, /* default */
		HM_ACTION_DEFAULT_SYSTEM_13, /* default */
		HM_ACTION_DEFAULT_SYSTEM_14, /* default */
		HM_ACTION_DEFAULT_SYSTEM_15, /* default */
		HM_ACTION_DEFAULT_SYSTEM_16, /* default */
		HM_ACTION_DEFAULT_SYSTEM_17, /* default */
		HM_ACTION_DEFAULT_SYSTEM_18, /* default */
		HM_ACTION_DEFAULT_SYSTEM_19, /* default */
		HM_ACTION_DEFAULT_SYSTEM_20, /* default */
		HM_ACTION_DEFAULT_SYSTEM_21, /* default */
		HM_ACTION_DEFAULT_SYSTEM_22, /* default */
		HM_ACTION_DEFAULT_SYSTEM_23, /* default */
		HM_ACTION_DEFAULT_SYSTEM_24, /* default */
		HM_ACTION_DEFAULT_SYSTEM_25, /* default */
		HM_ACTION_DEFAULT_SYSTEM_26, /* default */
		HM_ACTION_DEFAULT_SYSTEM_27, /* default */
		HM_ACTION_DEFAULT_SYSTEM_28, /* default */
		HM_ACTION_DEFAULT_SYSTEM_29, /* default */
		HM_ACTION_DEFAULT_SYSTEM_30, /* default */
		HM_ACTION_DEFAULT_SYSTEM_31, /* default */
		HM_ACTION_DEFAULT_SYSTEM_32, /* default */
		HM_ACTION_DEFAULT_SYSTEM_33, /* default */
		HM_ACTION_DEFAULT_SYSTEM_34, /* default */
		HM_ACTION_DEFAULT_SYSTEM_35, /* default */
	}},
};

/* Partition HM tables */
const struct hm_table hm_table_part_cfg[3] = {
	/* partition HM table 0 for idle partition */ { .level_action_error_code = {
		HM_ACTION_DEFAULT_PARTITION_0, /* default */
		HM_ACTION_DEFAULT_PARTITION_1, /* default */
		HM_ACTION_DEFAULT_PARTITION_2, /* default */
		HM_ACTION_DEFAULT_PARTITION_3, /* default */
		HM_ACTION_DEFAULT_PARTITION_4, /* default */
		HM_ACTION_DEFAULT_PARTITION_5, /* default */
		HM_ACTION_DEFAULT_PARTITION_6, /* default */
		HM_ACTION_DEFAULT_PARTITION_7, /* default */
		HM_ACTION_DEFAULT_PARTITION_8, /* default */
		HM_ACTION_DEFAULT_PARTITION_9, /* default */
		HM_ACTION_DEFAULT_PARTITION_10, /* default */
		HM_ACTION_DEFAULT_PARTITION_11, /* default */
		HM_ACTION_DEFAULT_PARTITION_12, /* default */
		HM_ACTION_DEFAULT_PARTITION_13, /* default */
		HM_ACTION_DEFAULT_PARTITION_14, /* default */
		HM_ACTION_DEFAULT_PARTITION_15, /* default */
		HM_ACTION_DEFAULT_PARTITION_16, /* default */
		HM_ACTION_DEFAULT_PARTITION_17, /* default */
		HM_ACTION_DEFAULT_PARTITION_18, /* default */
		HM_ACTION_DEFAULT_PARTITION_19, /* default */
		HM_ACTION_DEFAULT_PARTITION_20, /* default */
		HM_ACTION_DEFAULT_PARTITION_21, /* default */
		HM_ACTION_DEFAULT_PARTITION_22, /* default */
		HM_ACTION_DEFAULT_PARTITION_23, /* default */
		HM_ACTION_DEFAULT_PARTITION_24, /* default */
		HM_ACTION_DEFAULT_PARTITION_25, /* default */
		HM_ACTION_DEFAULT_PARTITION_26, /* default */
		HM_ACTION_DEFAULT_PARTITION_27, /* default */
		HM_ACTION_DEFAULT_PARTITION_28, /* default */
		HM_ACTION_DEFAULT_PARTITION_29, /* default */
		HM_ACTION_DEFAULT_PARTITION_30, /* default */
		HM_ACTION_DEFAULT_PARTITION_31, /* default */
		HM_ACTION_DEFAULT_PARTITION_32, /* default */
		HM_ACTION_DEFAULT_PARTITION_33, /* default */
		HM_ACTION_DEFAULT_PARTITION_34, /* default */
		HM_ACTION_DEFAULT_PARTITION_35, /* default */
	}},
	/* partition HM table 1 for partition 'part1' */ { .level_action_error_code = {
		HM_ACTION_DEFAULT_PARTITION_0, /* default */
		HM_ACTION_DEFAULT_PARTITION_1, /* default */
		HM_ACTION_DEFAULT_PARTITION_2, /* default */
		HM_ACTION_DEFAULT_PARTITION_3, /* default */
		HM_ACTION_DEFAULT_PARTITION_4, /* default */
		HM_ACTION_DEFAULT_PARTITION_5, /* default */
		HM_ACTION_DEFAULT_PARTITION_6, /* default */
		HM_ACTION_DEFAULT_PARTITION_7, /* default */
		HM_ACTION_DEFAULT_PARTITION_8, /* default */
		HM_ACTION_DEFAULT_PARTITION_9, /* default */
		HM_ACTION_DEFAULT_PARTITION_10, /* default */
		HM_ACTION_DEFAULT_PARTITION_11, /* default */
		HM_ACTION_DEFAULT_PARTITION_12, /* default */
		HM_ACTION_DEFAULT_PARTITION_13, /* default */
		HM_ACTION_DEFAULT_PARTITION_14, /* default */
		HM_ACTION_DEFAULT_PARTITION_15, /* default */
		HM_ACTION_DEFAULT_PARTITION_16, /* default */
		HM_ACTION_DEFAULT_PARTITION_17, /* default */
		HM_ACTION_DEFAULT_PARTITION_18, /* default */
		HM_ACTION_DEFAULT_PARTITION_19, /* default */
		HM_ACTION_DEFAULT_PARTITION_20, /* default */
		HM_ACTION_DEFAULT_PARTITION_21, /* default */
		HM_ACTION_DEFAULT_PARTITION_22, /* default */
		HM_ACTION_DEFAULT_PARTITION_23, /* default */
		HM_ACTION_DEFAULT_PARTITION_24, /* default */
		HM_ACTION_DEFAULT_PARTITION_25, /* default */
		HM_ACTION_DEFAULT_PARTITION_26, /* default */
		HM_ACTION_DEFAULT_PARTITION_27, /* default */
		HM_ACTION_DEFAULT_PARTITION_28, /* default */
		HM_ACTION_DEFAULT_PARTITION_29, /* default */
		HM_ACTION_DEFAULT_PARTITION_30, /* default */
		HM_ACTION_DEFAULT_PARTITION_31, /* default */
		HM_ACTION_DEFAULT_PARTITION_32, /* default */
		HM_ACTION_DEFAULT_PARTITION_33, /* default */
		HM_ACTION_DEFAULT_PARTITION_34, /* default */
		HM_ACTION_DEFAULT_PARTITION_35, /* default */
	}},
	/* partition HM table 2 for partition 'part2' */ { .level_action_error_code = {
		HM_ACTION_DEFAULT_PARTITION_0, /* default */
		HM_ACTION_DEFAULT_PARTITION_1, /* default */
		HM_ACTION_DEFAULT_PARTITION_2, /* default */
		HM_ACTION_DEFAULT_PARTITION_3, /* default */
		HM_ACTION_DEFAULT_PARTITION_4, /* default */
		HM_ACTION_DEFAULT_PARTITION_5, /* default */
		HM_ACTION_DEFAULT_PARTITION_6, /* default */
		HM_ACTION_DEFAULT_PARTITION_7, /* default */
		HM_ACTION_DEFAULT_PARTITION_8, /* default */
		HM_ACTION_DEFAULT_PARTITION_9, /* default */
		HM_ACTION_DEFAULT_PARTITION_10, /* default */
		HM_ACTION_DEFAULT_PARTITION_11, /* default */
		HM_ACTION_DEFAULT_PARTITION_12, /* default */
		HM_ACTION_DEFAULT_PARTITION_13, /* default */
		HM_ACTION_DEFAULT_PARTITION_14, /* default */
		HM_ACTION_DEFAULT_PARTITION_15, /* default */
		HM_ACTION_DEFAULT_PARTITION_16, /* default */
		HM_ACTION_DEFAULT_PARTITION_17, /* default */
		HM_ACTION_DEFAULT_PARTITION_18, /* default */
		HM_ACTION_DEFAULT_PARTITION_19, /* default */
		HM_ACTION_PARTITION_COLD_START,
		HM_ACTION_PARTITION_COLD_START,
		HM_ACTION_PARTITION_COLD_START,
		HM_ACTION_PARTITION_COLD_START,
		HM_ACTION_DEFAULT_PARTITION_24, /* default */
		HM_ACTION_DEFAULT_PARTITION_25, /* default */
		HM_ACTION_DEFAULT_PARTITION_26, /* default */
		HM_ACTION_DEFAULT_PARTITION_27, /* default */
		HM_ACTION_DEFAULT_PARTITION_28, /* default */
		HM_ACTION_DEFAULT_PARTITION_29, /* default */
		HM_ACTION_DEFAULT_PARTITION_30, /* default */
		HM_ACTION_DEFAULT_PARTITION_31, /* default */
		HM_ACTION_DEFAULT_PARTITION_32, /* default */
		HM_ACTION_DEFAULT_PARTITION_33, /* default */
		HM_ACTION_DEFAULT_PARTITION_34, /* default */
		HM_ACTION_DEFAULT_PARTITION_35, /* default */
	}},
};

/* mpu.c -- AUTOGENERATED -- DO NOT EDIT -- */
/* ab_gen_mpu_c.pl 2016-01-13 */

/* WARNING: THIS FILE LACKS THE FINAL MPU WINDOW CONFIGURATION */
/* WARNING: rerun ab_gen_mpu_c.pl with the final memory.xml for a valid configuration */

#include <arch_mpu_state.h>

/* MPU settings for all partitions (one per partition) */
const struct arch_mpu_part_cfg mpu_part_cfg[3] = {
	/* empty MPU configuration */
};

/* MPU settings for all tasks (one per task) */
const struct arch_mpu_task_cfg mpu_task_cfg[20] = {
	/* empty MPU configuration */
};

/* SHM configuration */
const struct shm_cfg shm_cfg[0] = {
	/* empty SHM configuration */
};
